add: CoRIM generator

diff --git a/testvector/rats/corim/Makefile b/testvector/rats/corim/Makefile
--- a/testvector/rats/corim/Makefile
+++ b/testvector/rats/corim/Makefile
@@ -4,30 +4,29 @@
 # SPDX-License-Identifier: BSD-2-Clause
 #
 
-PSA_TOKEN_EVIDENCE_CBOR=psa_token_evidence.cbor
-PSA_TOKEN_EVIDENCE=$(PSA_TOKEN_EVIDENCE_CBOR:.cbor=.attester.es256.cose)
-.PRECIOUS: $(PSA_TOKEN_EVIDENCE_CBOR)
+CORIM_CBOR=corim-generic-eat.cbor
+.PRECIOUS: $(CORIM_CBOR)
 
 .PHONY: all
-all: $(PSA_TOKEN_EVIDENCE) eat_evidence.attester.es256.cose
+all: $(CORIM_CBOR)
 
 # set cddl file
-CDDL_FILE=../cddl/psa-token.cddl
+CDDL_FILE=../../cddl/corim.cddl
 
 # load generic rules
-include ../scripts/common.mk
+include ../../scripts/common.mk
 
 # do not deterministically encode referring to the veraison/services/end-to-end/input/psa-evidence.cbor
 psa_token_evidence.gdiag: psa_token_evidence.rediag
 	RUBYOPT="-W0" CBOR_DIAG_CDDL=$(CDDL_FILE) diag2diag.rb -e -aref -ae -adt $< > $@
 
 .PHONY: test
-test: $(PSA_TOKEN_EVIDENCE_CBOR) $(CDDL_FILE)
+test: $(CORIM_CBOR) $(CDDL_FILE)
 	@echo $(TEST_COMMAND) $<
 	@if $(TEST_COMMAND) $<; then \
-		echo "[SUCCESS] Generated PSA Token binary $< matches to the CDDL of PSA Token."; \
+		echo "[SUCCESS] Generated CoRIM binary $< matches to the CDDL of CoRIM."; \
 	else \
-		echo "[FAIL] Generated PSA Token binary $< doesn't match to the CDDL of PSA Token."; exit 1; \
+		echo "[FAIL] Generated CoRIM binary $< doesn't match to the CDDL of CoRIM`."; exit 1; \
 	fi
 
 .PHONY: clean
